# CUDA

[[CUDA100]]
arch = "x86_64"
git-tree-sha1 = "648368f3ef329250b1b808b75f5c8512231d3501"
lazy = true
os = "macos"

    [[CUDA100.download]]
    sha256 = "23414ecaafa7a2bb990b662e0196c93ad04008c70e464d4f0a31434aca45335c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.0.130+2/CUDA.v10.0.130.x86_64-apple-darwin.tar.gz"

[[CUDA100]]
arch = "x86_64"
git-tree-sha1 = "b0592237d8a9a7dd5f9c8efac9ddda71cc901f69"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA100.download]]
    sha256 = "6551c4d18c0d1c60d6eeeab29dab04c26e1788c6a4abe3d285ab2178389d599d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.0.130+2/CUDA.v10.0.130.x86_64-linux-gnu.tar.gz"

[[CUDA100]]
arch = "x86_64"
git-tree-sha1 = "e7fd7333a3717ae4dbfc3a2151739e20c7c5e574"
lazy = true
os = "windows"

    [[CUDA100.download]]
    sha256 = "155679a256dceaff7f2abdeffd15d2fd45f005237fa52381d6fc784954adeb4a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.0.130+2/CUDA.v10.0.130.x86_64-w64-mingw32.tar.gz"


[[CUDA101]]
arch = "x86_64"
git-tree-sha1 = "e78c578ea87e45aacd782cb3f8a60fd55e5af830"
lazy = true
os = "macos"

    [[CUDA101.download]]
    sha256 = "7659baa56978423606cfac140a9ddf93bf6883f26acb68ff32e79102ddb408a8"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.1.243+4/CUDA.v10.1.243.x86_64-apple-darwin.tar.gz"

[[CUDA101]]
arch = "x86_64"
git-tree-sha1 = "f049c2824a217dc29dbf657e5cdf0f8adafca77a"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA101.download]]
    sha256 = "e498243dfab30e9568639b23d1d11949e920b8a0c2f91a5b1a385cdd8ca0ef02"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.1.243+4/CUDA.v10.1.243.x86_64-linux-gnu.tar.gz"

[[CUDA101]]
arch = "x86_64"
git-tree-sha1 = "ab5e0b50d8cd099bdeef240b56224ff252a79814"
lazy = true
os = "windows"

    [[CUDA101.download]]
    sha256 = "20266410fe2489c63b8be85dcc3edc31e1892affd7a16354dd184a74e46c6e9b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.1.243+4/CUDA.v10.1.243.x86_64-w64-mingw32.tar.gz"

[[CUDA102]]
arch = "x86_64"
git-tree-sha1 = "4902a30cc1c0dd4d42aa245c4e2d2d9e54e7cbc0"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA102.download]]
    sha256 = "903c4e018891697aa6ba584c7c93b3d4c66e04f3c0d216925fd1afea0fbeae4f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.2.89+4/CUDA.v10.2.89.x86_64-linux-gnu.tar.gz"

[[CUDA102]]
arch = "x86_64"
git-tree-sha1 = "d96ad7b35e435dc21f6a9072e8e02a44f2655a0c"
lazy = true
os = "windows"

    [[CUDA102.download]]
    sha256 = "a1a3a2c73fa8fb17e317b41300c85659ccf43edf6e15e1af2396003d3e14359d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.2.89+4/CUDA.v10.2.89.x86_64-w64-mingw32.tar.gz"

[[CUDA110]]
arch = "powerpc64le"
git-tree-sha1 = "b22672705ca4f00c784a3f9d58619408d4af9de0"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA110.download]]
    sha256 = "396dc85ffa4686c2c6822df25419c5bd6e25317ab725a672818dbb79a761e952"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.0.3+2/CUDA.v11.0.3.powerpc64le-linux-gnu.tar.gz"

[[CUDA110]]
arch = "x86_64"
git-tree-sha1 = "6b1a60793e5e98abdcfc3724cfa22b2a5348dc09"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA110.download]]
    sha256 = "5bbe675257e19eea350bf84f0e27ec36c2f35d2222e0e7cb4d50a00509d6aac0"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.0.3+2/CUDA.v11.0.3.x86_64-linux-gnu.tar.gz"

[[CUDA110]]
arch = "x86_64"
git-tree-sha1 = "c54ef6151a5f3dc7e1a053f1c1a9f85352dca3e4"
lazy = true
os = "windows"

    [[CUDA110.download]]
    sha256 = "80d49fdf47715132da41842331718a73fd1dc544c9a8d09a9610a64791d1fb5d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.0.3+2/CUDA.v11.0.3.x86_64-w64-mingw32.tar.gz"

[[CUDA111]]
arch = "powerpc64le"
git-tree-sha1 = "44dba03dc848a148c9d2430354bf7e52e216364c"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA111.download]]
    sha256 = "1ec19f75bd70781d657dde3ae11994828756ffee775564d96a038af1aebd97e7"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.1.1+1/CUDA.v11.1.1.powerpc64le-linux-gnu.tar.gz"

[[CUDA111]]
arch = "x86_64"
git-tree-sha1 = "48c41dccb8db0c9aa9483267cb33719207abe4c1"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA111.download]]
    sha256 = "e74d2031db1bb9610f14d9f7e0bf050c8d141a83e3e13f6fb2e41c5e37b6ea16"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.1.1+1/CUDA.v11.1.1.x86_64-linux-gnu.tar.gz"

[[CUDA111]]
arch = "x86_64"
git-tree-sha1 = "6c9c066b7cbed1a2dff086b79fb6c3ab8dd70140"
lazy = true
os = "windows"

    [[CUDA111.download]]
    sha256 = "e5e4f14b10bd80bda65527b4ac9994eac089e21c392f75c88ff355a5eabcc75b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.1.1+1/CUDA.v11.1.1.x86_64-w64-mingw32.tar.gz"


# CUDNN

[[CUDNN_CUDA101]]
arch = "x86_64"
git-tree-sha1 = "ef45f9aaa18e23f1360eb6cb06c89ead81752f02"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA101.download]]
    sha256 = "b72bac08f0c878a350b35c69356a85a5cd578b0e457ac68c9989f6bf055b9880"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA101_jll.jl/releases/download/CUDNN_CUDA101-v8.0.4+0/CUDNN_CUDA101.v8.0.4.x86_64-linux-gnu.tar.gz"

[[CUDNN_CUDA101]]
arch = "powerpc64le"
git-tree-sha1 = "5d3b42f300c3a87ab8858e86aa81f9caf4b12d1a"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA101.download]]
    sha256 = "a40f9e83864b339af28a7012e9f027b932aa0a882a7dd2a63bb9a94fc58e111e"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA101_jll.jl/releases/download/CUDNN_CUDA101-v8.0.4+0/CUDNN_CUDA101.v8.0.4.powerpc64le-linux-gnu.tar.gz"

[[CUDNN_CUDA101]]
arch = "x86_64"
git-tree-sha1 = "29e0f0db94f0a4aa539ffc8593dd07f0f209965c"
lazy = true
os = "windows"

    [[CUDNN_CUDA101.download]]
    sha256 = "ac23cbb9ccde477ec2fad4d2efa1b891c8c6079de5df06f6f9d7f4871343d23f"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA101_jll.jl/releases/download/CUDNN_CUDA101-v8.0.4+0/CUDNN_CUDA101.v8.0.4.x86_64-w64-mingw32.tar.gz"

[[CUDNN_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "85541be8da184b27fcca8772fa6989008fa76c72"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA102.download]]
    sha256 = "ae85091dafd20e4f070148825d247a9a3ab8066888833e88b01a3d30571954f5"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA102_jll.jl/releases/download/CUDNN_CUDA102-v8.0.4+0/CUDNN_CUDA102.v8.0.4.x86_64-linux-gnu.tar.gz"

[[CUDNN_CUDA102]]
arch = "powerpc64le"
git-tree-sha1 = "bc48bc3f534400aa4a841fa5886f794ee458d380"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA102.download]]
    sha256 = "83fdecd9b53c83f4b024beb24cf93a755b6a5a53011d4783e8bf06cadee47ffe"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA102_jll.jl/releases/download/CUDNN_CUDA102-v8.0.4+0/CUDNN_CUDA102.v8.0.4.powerpc64le-linux-gnu.tar.gz"

[[CUDNN_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "d1e2f396182c9319f1ae2e7f020a3b969ccb8cc6"
lazy = true
os = "windows"

    [[CUDNN_CUDA102.download]]
    sha256 = "be6a8c9892bd397ab055eec3ccffcf8e706ea8e2f0e4b49223eba895b38d2fe1"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA102_jll.jl/releases/download/CUDNN_CUDA102-v8.0.4+0/CUDNN_CUDA102.v8.0.4.x86_64-w64-mingw32.tar.gz"

[[CUDNN_CUDA110]]
arch = "x86_64"
git-tree-sha1 = "20bd3307e0252b00c171e1753f6424bbbdc5678f"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA110.download]]
    sha256 = "5c238d29679825b1bc32942788e2863b67bb225e7cf20b8a476f5e2ce4bfb4c0"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA110_jll.jl/releases/download/CUDNN_CUDA110-v8.0.4+0/CUDNN_CUDA110.v8.0.4.x86_64-linux-gnu.tar.gz"

[[CUDNN_CUDA110]]
arch = "powerpc64le"
git-tree-sha1 = "dafc11890c3db5cc524be294fe39a66fd69e7b30"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA110.download]]
    sha256 = "7205bf543f0eea04b7ae6a33440ae7a92e50a9d745a1820920d552d87c2c2377"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA110_jll.jl/releases/download/CUDNN_CUDA110-v8.0.4+0/CUDNN_CUDA110.v8.0.4.powerpc64le-linux-gnu.tar.gz"

[[CUDNN_CUDA110]]
arch = "x86_64"
git-tree-sha1 = "41cfcc3efda2b50f60b3429d5ecf624f25feb89c"
lazy = true
os = "windows"

    [[CUDNN_CUDA110.download]]
    sha256 = "88e1d0ac18aec826d6cf15c25e26a37861dbf8a940fa0051518eeff967915259"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA110_jll.jl/releases/download/CUDNN_CUDA110-v8.0.4+0/CUDNN_CUDA110.v8.0.4.x86_64-w64-mingw32.tar.gz"

[[CUDNN_CUDA111]]
arch = "x86_64"
git-tree-sha1 = "c1f953962cc13e4a55f7b2333fb212e7f5c08817"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA111.download]]
    sha256 = "850c242ae87c700785d069f45c0f99d5690b529295efc176ab53ac37be80de83"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA111_jll.jl/releases/download/CUDNN_CUDA111-v8.0.4+0/CUDNN_CUDA111.v8.0.4.x86_64-linux-gnu.tar.gz"

[[CUDNN_CUDA111]]
arch = "powerpc64le"
git-tree-sha1 = "d9fe82ad403da05636d1e30c1dd560722e98412d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA111.download]]
    sha256 = "4dd204e0d2eda3dd7e45f4e259dbd11cae6fb6ac429aabf0d0027222f4c3f364"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA111_jll.jl/releases/download/CUDNN_CUDA111-v8.0.4+0/CUDNN_CUDA111.v8.0.4.powerpc64le-linux-gnu.tar.gz"

[[CUDNN_CUDA111]]
arch = "x86_64"
git-tree-sha1 = "194b57428903281322b7e941d4ba7f744c01e0dd"
lazy = true
os = "windows"

    [[CUDNN_CUDA111.download]]
    sha256 = "343a676eee0559e0447d3c9a59f6a24305c9a07f2ded8c338c4131614bd17b30"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA111_jll.jl/releases/download/CUDNN_CUDA111-v8.0.4+0/CUDNN_CUDA111.v8.0.4.x86_64-w64-mingw32.tar.gz"


# CUTENSOR

[[CUTENSOR_CUDA101]]
arch = "x86_64"
git-tree-sha1 = "f1db721383620b9d06b45c57d211c85c40133e5a"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA101.download]]
    sha256 = "a4905dc2539b0114487f9a742f11f7932095c19817c5152f4902c3db68b8b2d2"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA101_jll.jl/releases/download/CUTENSOR_CUDA101-v1.2.1+0/CUTENSOR_CUDA101.v1.2.1.x86_64-linux-gnu.tar.gz"

[[CUTENSOR_CUDA101]]
arch = "powerpc64le"
git-tree-sha1 = "83889538efc9a5eb5dd20e885a55e3efdac65f35"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA101.download]]
    sha256 = "aa658ae8cb779530d8c5e411282bf1e5ff6743f8093a3a9dfdd60797c3a1e55d"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA101_jll.jl/releases/download/CUTENSOR_CUDA101-v1.2.1+0/CUTENSOR_CUDA101.v1.2.1.powerpc64le-linux-gnu.tar.gz"

[[CUTENSOR_CUDA101]]
arch = "x86_64"
git-tree-sha1 = "21f5d6a83306fdca4fe7676e3d5cf5e7ca2e5ce9"
lazy = true
os = "windows"

    [[CUTENSOR_CUDA101.download]]
    sha256 = "23641941e648d2ce9622c422dbcb522b3c6f0be665cf4e181bbc3ae87c69158f"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA101_jll.jl/releases/download/CUTENSOR_CUDA101-v1.2.1+0/CUTENSOR_CUDA101.v1.2.1.x86_64-w64-mingw32.tar.gz"

[[CUTENSOR_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "03cdeb3db858287244c2530d75f0a845b90c48b4"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA102.download]]
    sha256 = "dbe99a6a5a2f68a2922e2c1006a451cad523a521004409fb80ca883303a85dbf"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA102_jll.jl/releases/download/CUTENSOR_CUDA102-v1.2.1+0/CUTENSOR_CUDA102.v1.2.1.x86_64-linux-gnu.tar.gz"

[[CUTENSOR_CUDA102]]
arch = "powerpc64le"
git-tree-sha1 = "029afc64d39bc2993604c9eb6a15ed8c32f21d57"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA102.download]]
    sha256 = "44492dc223f5e7501fec90eb8f35ea68a7feb2284cfdc452d8ee533ddb28475d"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA102_jll.jl/releases/download/CUTENSOR_CUDA102-v1.2.1+0/CUTENSOR_CUDA102.v1.2.1.powerpc64le-linux-gnu.tar.gz"

[[CUTENSOR_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "cbd0fa8210b55e659dcbd4a37194812c7edf6be7"
lazy = true
os = "windows"

    [[CUTENSOR_CUDA102.download]]
    sha256 = "c8e3e4be487245342ddf111fe487b54c6a2159b212d54277c80d455a184f9b6d"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA102_jll.jl/releases/download/CUTENSOR_CUDA102-v1.2.1+0/CUTENSOR_CUDA102.v1.2.1.x86_64-w64-mingw32.tar.gz"

[[CUTENSOR_CUDA110]]
arch = "x86_64"
git-tree-sha1 = "d044e8d51eb58575dbce05d6ad981cdf5d18ded6"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA110.download]]
    sha256 = "187bc84e8d55c75123e114fd1e5be0ec84131b27ad8520428893517e300a993d"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.1+0/CUTENSOR_CUDA110.v1.2.1.x86_64-linux-gnu.tar.gz"

[[CUTENSOR_CUDA110]]
arch = "powerpc64le"
git-tree-sha1 = "97dc9b8f598d2ceefaf1baa7e38831e8fecceece"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA110.download]]
    sha256 = "78bfe4bfcac45d774b7a01b136aa9dd34c17ca0574d174f81e098912e5523866"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.1+0/CUTENSOR_CUDA110.v1.2.1.powerpc64le-linux-gnu.tar.gz"

[[CUTENSOR_CUDA110]]
arch = "x86_64"
git-tree-sha1 = "12aac82209fce6ae068e5a3e73fb3aeccc915b29"
lazy = true
os = "windows"

    [[CUTENSOR_CUDA110.download]]
    sha256 = "0dbaf32428e877f2f4a119c02e664a5f2f274e3b9c77fd1a355b00a8128f6e17"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.1+0/CUTENSOR_CUDA110.v1.2.1.x86_64-w64-mingw32.tar.gz"

[[CUTENSOR_CUDA111]]
arch = "x86_64"
git-tree-sha1 = "ac25f8a4fc72584e696bd007b229fd2921b34062"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA111.download]]
    sha256 = "36c1d5f2d00d1387aa4c6b65ae96da0c660728c091d30f8b4100790186fde3bf"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA111_jll.jl/releases/download/CUTENSOR_CUDA111-v1.2.1+0/CUTENSOR_CUDA111.v1.2.1.x86_64-linux-gnu.tar.gz"

[[CUTENSOR_CUDA111]]
arch = "powerpc64le"
git-tree-sha1 = "2b2cf1b9ada77a656b72334093b4519eb73e821f"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA111.download]]
    sha256 = "1fbcc5c9154ec118e7a6450cffc8d91b3e8de6ea7d12d91e28e432010d690822"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA111_jll.jl/releases/download/CUTENSOR_CUDA111-v1.2.1+0/CUTENSOR_CUDA111.v1.2.1.powerpc64le-linux-gnu.tar.gz"

[[CUTENSOR_CUDA111]]
arch = "x86_64"
git-tree-sha1 = "1af4317261411b403eee62561b401a92b6b49b3b"
lazy = true
os = "windows"

    [[CUTENSOR_CUDA111.download]]
    sha256 = "2bcc0e55016ed62f33b60a0b69085f1ab287de87bc52a82fba91ff0400ab1ece"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA111_jll.jl/releases/download/CUTENSOR_CUDA111-v1.2.1+0/CUTENSOR_CUDA111.v1.2.1.x86_64-w64-mingw32.tar.gz"

